/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResendVerificationRouteImport } from './routes/resend-verification'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsOrganizationIdRouteImport } from './routes/clubs.$organizationId'
import { Route as ClubsNewRouteImport } from './routes/clubs.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ViewOrganizationSlugIndexRouteImport } from './routes/view.$organizationSlug.index'
import { Route as OOrganizationSlugLLeagueIdRouteImport } from './routes/o.$organizationSlug.l.$leagueId'
import { Route as ViewOrganizationSlugLLeagueIdRouteImport } from './routes/view.$organizationSlug.l.$leagueId'
import { Route as OOrganizationSlugLLeagueIdIndexRouteImport } from './routes/o.$organizationSlug.l.$leagueId.index'
import { Route as OOrganizationSlugLLeagueIdHistoryRouteImport } from './routes/o.$organizationSlug.l.$leagueId.history'
import { Route as OOrganizationSlugLLeagueIdRoundRouteImport } from './routes/o.$organizationSlug.l.$leagueId.round'
import { Route as OOrganizationSlugLLeagueIdSettingsRouteImport } from './routes/o.$organizationSlug.l.$leagueId.settings'
import { Route as ViewOrganizationSlugLLeagueIdIndexRouteImport } from './routes/view.$organizationSlug.l.$leagueId.index'
import { Route as ViewOrganizationSlugLLeagueIdHistoryRouteImport } from './routes/view.$organizationSlug.l.$leagueId.history'
import { Route as ViewOrganizationSlugLLeagueIdRoundRouteImport } from './routes/view.$organizationSlug.l.$leagueId.round'
import { Route as OOrganizationSlugLLeagueIdLeaguesNewRouteImport } from './routes/o.$organizationSlug.l.$leagueId.leagues.new'
import { Route as OOrganizationSlugLLeagueIdPlayerPlayerIdRouteImport } from './routes/o.$organizationSlug.l.$leagueId.player.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationRoute = ResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsOrganizationIdRoute = ClubsOrganizationIdRouteImport.update({
  id: '/clubs/$organizationId',
  path: '/clubs/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsNewRoute = ClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewOrganizationSlugIndexRoute =
  ViewOrganizationSlugIndexRouteImport.update({
    id: '/view/$organizationSlug/',
    path: '/view/$organizationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationSlugLLeagueIdRoute =
  OOrganizationSlugLLeagueIdRouteImport.update({
    id: '/o/$organizationSlug/l/$leagueId',
    path: '/o/$organizationSlug/l/$leagueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ViewOrganizationSlugLLeagueIdRoute =
  ViewOrganizationSlugLLeagueIdRouteImport.update({
    id: '/view/$organizationSlug/l/$leagueId',
    path: '/view/$organizationSlug/l/$leagueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationSlugLLeagueIdIndexRoute =
  OOrganizationSlugLLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)
const OOrganizationSlugLLeagueIdHistoryRoute =
  OOrganizationSlugLLeagueIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)
const OOrganizationSlugLLeagueIdRoundRoute =
  OOrganizationSlugLLeagueIdRoundRouteImport.update({
    id: '/round',
    path: '/round',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)
const OOrganizationSlugLLeagueIdSettingsRoute =
  OOrganizationSlugLLeagueIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)
const ViewOrganizationSlugLLeagueIdIndexRoute =
  ViewOrganizationSlugLLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ViewOrganizationSlugLLeagueIdRoute,
  } as any)
const ViewOrganizationSlugLLeagueIdHistoryRoute =
  ViewOrganizationSlugLLeagueIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ViewOrganizationSlugLLeagueIdRoute,
  } as any)
const ViewOrganizationSlugLLeagueIdRoundRoute =
  ViewOrganizationSlugLLeagueIdRoundRouteImport.update({
    id: '/round',
    path: '/round',
    getParentRoute: () => ViewOrganizationSlugLLeagueIdRoute,
  } as any)
const OOrganizationSlugLLeagueIdLeaguesNewRoute =
  OOrganizationSlugLLeagueIdLeaguesNewRouteImport.update({
    id: '/leagues/new',
    path: '/leagues/new',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)
const OOrganizationSlugLLeagueIdPlayerPlayerIdRoute =
  OOrganizationSlugLLeagueIdPlayerPlayerIdRouteImport.update({
    id: '/player/$playerId',
    path: '/player/$playerId',
    getParentRoute: () => OOrganizationSlugLLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$organizationId': typeof ClubsOrganizationIdRoute
  '/clubs/new': typeof ClubsNewRoute
  '/clubs/': typeof ClubsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/view/$organizationSlug/': typeof ViewOrganizationSlugIndexRoute
  '/o/$organizationSlug/l/$leagueId': typeof OOrganizationSlugLLeagueIdRouteWithChildren
  '/view/$organizationSlug/l/$leagueId': typeof ViewOrganizationSlugLLeagueIdRouteWithChildren
  '/o/$organizationSlug/l/$leagueId/history': typeof OOrganizationSlugLLeagueIdHistoryRoute
  '/o/$organizationSlug/l/$leagueId/round': typeof OOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId/settings': typeof OOrganizationSlugLLeagueIdSettingsRoute
  '/view/$organizationSlug/l/$leagueId/history': typeof ViewOrganizationSlugLLeagueIdHistoryRoute
  '/view/$organizationSlug/l/$leagueId/round': typeof ViewOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId/': typeof OOrganizationSlugLLeagueIdIndexRoute
  '/view/$organizationSlug/l/$leagueId/': typeof ViewOrganizationSlugLLeagueIdIndexRoute
  '/o/$organizationSlug/l/$leagueId/leagues/new': typeof OOrganizationSlugLLeagueIdLeaguesNewRoute
  '/o/$organizationSlug/l/$leagueId/player/$playerId': typeof OOrganizationSlugLLeagueIdPlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$organizationId': typeof ClubsOrganizationIdRoute
  '/clubs/new': typeof ClubsNewRoute
  '/clubs': typeof ClubsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/view/$organizationSlug': typeof ViewOrganizationSlugIndexRoute
  '/o/$organizationSlug/l/$leagueId/history': typeof OOrganizationSlugLLeagueIdHistoryRoute
  '/o/$organizationSlug/l/$leagueId/round': typeof OOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId/settings': typeof OOrganizationSlugLLeagueIdSettingsRoute
  '/view/$organizationSlug/l/$leagueId/history': typeof ViewOrganizationSlugLLeagueIdHistoryRoute
  '/view/$organizationSlug/l/$leagueId/round': typeof ViewOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId': typeof OOrganizationSlugLLeagueIdIndexRoute
  '/view/$organizationSlug/l/$leagueId': typeof ViewOrganizationSlugLLeagueIdIndexRoute
  '/o/$organizationSlug/l/$leagueId/leagues/new': typeof OOrganizationSlugLLeagueIdLeaguesNewRoute
  '/o/$organizationSlug/l/$leagueId/player/$playerId': typeof OOrganizationSlugLLeagueIdPlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$organizationId': typeof ClubsOrganizationIdRoute
  '/clubs/new': typeof ClubsNewRoute
  '/clubs/': typeof ClubsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/view/$organizationSlug/': typeof ViewOrganizationSlugIndexRoute
  '/o/$organizationSlug/l/$leagueId': typeof OOrganizationSlugLLeagueIdRouteWithChildren
  '/view/$organizationSlug/l/$leagueId': typeof ViewOrganizationSlugLLeagueIdRouteWithChildren
  '/o/$organizationSlug/l/$leagueId/history': typeof OOrganizationSlugLLeagueIdHistoryRoute
  '/o/$organizationSlug/l/$leagueId/round': typeof OOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId/settings': typeof OOrganizationSlugLLeagueIdSettingsRoute
  '/view/$organizationSlug/l/$leagueId/history': typeof ViewOrganizationSlugLLeagueIdHistoryRoute
  '/view/$organizationSlug/l/$leagueId/round': typeof ViewOrganizationSlugLLeagueIdRoundRoute
  '/o/$organizationSlug/l/$leagueId/': typeof OOrganizationSlugLLeagueIdIndexRoute
  '/view/$organizationSlug/l/$leagueId/': typeof ViewOrganizationSlugLLeagueIdIndexRoute
  '/o/$organizationSlug/l/$leagueId/leagues/new': typeof OOrganizationSlugLLeagueIdLeaguesNewRoute
  '/o/$organizationSlug/l/$leagueId/player/$playerId': typeof OOrganizationSlugLLeagueIdPlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/clubs/$organizationId'
    | '/clubs/new'
    | '/clubs/'
    | '/api/auth/$'
    | '/view/$organizationSlug/'
    | '/o/$organizationSlug/l/$leagueId'
    | '/view/$organizationSlug/l/$leagueId'
    | '/o/$organizationSlug/l/$leagueId/history'
    | '/o/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId/settings'
    | '/view/$organizationSlug/l/$leagueId/history'
    | '/view/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId/'
    | '/view/$organizationSlug/l/$leagueId/'
    | '/o/$organizationSlug/l/$leagueId/leagues/new'
    | '/o/$organizationSlug/l/$leagueId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/clubs/$organizationId'
    | '/clubs/new'
    | '/clubs'
    | '/api/auth/$'
    | '/view/$organizationSlug'
    | '/o/$organizationSlug/l/$leagueId/history'
    | '/o/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId/settings'
    | '/view/$organizationSlug/l/$leagueId/history'
    | '/view/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId'
    | '/view/$organizationSlug/l/$leagueId'
    | '/o/$organizationSlug/l/$leagueId/leagues/new'
    | '/o/$organizationSlug/l/$leagueId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/clubs/$organizationId'
    | '/clubs/new'
    | '/clubs/'
    | '/api/auth/$'
    | '/view/$organizationSlug/'
    | '/o/$organizationSlug/l/$leagueId'
    | '/view/$organizationSlug/l/$leagueId'
    | '/o/$organizationSlug/l/$leagueId/history'
    | '/o/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId/settings'
    | '/view/$organizationSlug/l/$leagueId/history'
    | '/view/$organizationSlug/l/$leagueId/round'
    | '/o/$organizationSlug/l/$leagueId/'
    | '/view/$organizationSlug/l/$leagueId/'
    | '/o/$organizationSlug/l/$leagueId/leagues/new'
    | '/o/$organizationSlug/l/$leagueId/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResendVerificationRoute: typeof ResendVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ClubsOrganizationIdRoute: typeof ClubsOrganizationIdRoute
  ClubsNewRoute: typeof ClubsNewRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ViewOrganizationSlugIndexRoute: typeof ViewOrganizationSlugIndexRoute
  OOrganizationSlugLLeagueIdRoute: typeof OOrganizationSlugLLeagueIdRouteWithChildren
  ViewOrganizationSlugLLeagueIdRoute: typeof ViewOrganizationSlugLLeagueIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification': {
      id: '/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof ResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$organizationId': {
      id: '/clubs/$organizationId'
      path: '/clubs/$organizationId'
      fullPath: '/clubs/$organizationId'
      preLoaderRoute: typeof ClubsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/new': {
      id: '/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof ClubsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$organizationSlug/': {
      id: '/view/$organizationSlug/'
      path: '/view/$organizationSlug'
      fullPath: '/view/$organizationSlug/'
      preLoaderRoute: typeof ViewOrganizationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationSlug/l/$leagueId': {
      id: '/o/$organizationSlug/l/$leagueId'
      path: '/o/$organizationSlug/l/$leagueId'
      fullPath: '/o/$organizationSlug/l/$leagueId'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$organizationSlug/l/$leagueId': {
      id: '/view/$organizationSlug/l/$leagueId'
      path: '/view/$organizationSlug/l/$leagueId'
      fullPath: '/view/$organizationSlug/l/$leagueId'
      preLoaderRoute: typeof ViewOrganizationSlugLLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationSlug/l/$leagueId/': {
      id: '/o/$organizationSlug/l/$leagueId/'
      path: '/'
      fullPath: '/o/$organizationSlug/l/$leagueId/'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdIndexRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
    '/o/$organizationSlug/l/$leagueId/history': {
      id: '/o/$organizationSlug/l/$leagueId/history'
      path: '/history'
      fullPath: '/o/$organizationSlug/l/$leagueId/history'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdHistoryRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
    '/o/$organizationSlug/l/$leagueId/round': {
      id: '/o/$organizationSlug/l/$leagueId/round'
      path: '/round'
      fullPath: '/o/$organizationSlug/l/$leagueId/round'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdRoundRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
    '/o/$organizationSlug/l/$leagueId/settings': {
      id: '/o/$organizationSlug/l/$leagueId/settings'
      path: '/settings'
      fullPath: '/o/$organizationSlug/l/$leagueId/settings'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdSettingsRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
    '/view/$organizationSlug/l/$leagueId/': {
      id: '/view/$organizationSlug/l/$leagueId/'
      path: '/'
      fullPath: '/view/$organizationSlug/l/$leagueId/'
      preLoaderRoute: typeof ViewOrganizationSlugLLeagueIdIndexRouteImport
      parentRoute: typeof ViewOrganizationSlugLLeagueIdRoute
    }
    '/view/$organizationSlug/l/$leagueId/history': {
      id: '/view/$organizationSlug/l/$leagueId/history'
      path: '/history'
      fullPath: '/view/$organizationSlug/l/$leagueId/history'
      preLoaderRoute: typeof ViewOrganizationSlugLLeagueIdHistoryRouteImport
      parentRoute: typeof ViewOrganizationSlugLLeagueIdRoute
    }
    '/view/$organizationSlug/l/$leagueId/round': {
      id: '/view/$organizationSlug/l/$leagueId/round'
      path: '/round'
      fullPath: '/view/$organizationSlug/l/$leagueId/round'
      preLoaderRoute: typeof ViewOrganizationSlugLLeagueIdRoundRouteImport
      parentRoute: typeof ViewOrganizationSlugLLeagueIdRoute
    }
    '/o/$organizationSlug/l/$leagueId/leagues/new': {
      id: '/o/$organizationSlug/l/$leagueId/leagues/new'
      path: '/leagues/new'
      fullPath: '/o/$organizationSlug/l/$leagueId/leagues/new'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdLeaguesNewRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
    '/o/$organizationSlug/l/$leagueId/player/$playerId': {
      id: '/o/$organizationSlug/l/$leagueId/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/o/$organizationSlug/l/$leagueId/player/$playerId'
      preLoaderRoute: typeof OOrganizationSlugLLeagueIdPlayerPlayerIdRouteImport
      parentRoute: typeof OOrganizationSlugLLeagueIdRoute
    }
  }
}

interface OOrganizationSlugLLeagueIdRouteChildren {
  OOrganizationSlugLLeagueIdHistoryRoute: typeof OOrganizationSlugLLeagueIdHistoryRoute
  OOrganizationSlugLLeagueIdRoundRoute: typeof OOrganizationSlugLLeagueIdRoundRoute
  OOrganizationSlugLLeagueIdSettingsRoute: typeof OOrganizationSlugLLeagueIdSettingsRoute
  OOrganizationSlugLLeagueIdIndexRoute: typeof OOrganizationSlugLLeagueIdIndexRoute
  OOrganizationSlugLLeagueIdLeaguesNewRoute: typeof OOrganizationSlugLLeagueIdLeaguesNewRoute
  OOrganizationSlugLLeagueIdPlayerPlayerIdRoute: typeof OOrganizationSlugLLeagueIdPlayerPlayerIdRoute
}

const OOrganizationSlugLLeagueIdRouteChildren: OOrganizationSlugLLeagueIdRouteChildren =
  {
    OOrganizationSlugLLeagueIdHistoryRoute:
      OOrganizationSlugLLeagueIdHistoryRoute,
    OOrganizationSlugLLeagueIdRoundRoute: OOrganizationSlugLLeagueIdRoundRoute,
    OOrganizationSlugLLeagueIdSettingsRoute:
      OOrganizationSlugLLeagueIdSettingsRoute,
    OOrganizationSlugLLeagueIdIndexRoute: OOrganizationSlugLLeagueIdIndexRoute,
    OOrganizationSlugLLeagueIdLeaguesNewRoute:
      OOrganizationSlugLLeagueIdLeaguesNewRoute,
    OOrganizationSlugLLeagueIdPlayerPlayerIdRoute:
      OOrganizationSlugLLeagueIdPlayerPlayerIdRoute,
  }

const OOrganizationSlugLLeagueIdRouteWithChildren =
  OOrganizationSlugLLeagueIdRoute._addFileChildren(
    OOrganizationSlugLLeagueIdRouteChildren,
  )

interface ViewOrganizationSlugLLeagueIdRouteChildren {
  ViewOrganizationSlugLLeagueIdHistoryRoute: typeof ViewOrganizationSlugLLeagueIdHistoryRoute
  ViewOrganizationSlugLLeagueIdRoundRoute: typeof ViewOrganizationSlugLLeagueIdRoundRoute
  ViewOrganizationSlugLLeagueIdIndexRoute: typeof ViewOrganizationSlugLLeagueIdIndexRoute
}

const ViewOrganizationSlugLLeagueIdRouteChildren: ViewOrganizationSlugLLeagueIdRouteChildren =
  {
    ViewOrganizationSlugLLeagueIdHistoryRoute:
      ViewOrganizationSlugLLeagueIdHistoryRoute,
    ViewOrganizationSlugLLeagueIdRoundRoute:
      ViewOrganizationSlugLLeagueIdRoundRoute,
    ViewOrganizationSlugLLeagueIdIndexRoute:
      ViewOrganizationSlugLLeagueIdIndexRoute,
  }

const ViewOrganizationSlugLLeagueIdRouteWithChildren =
  ViewOrganizationSlugLLeagueIdRoute._addFileChildren(
    ViewOrganizationSlugLLeagueIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResendVerificationRoute: ResendVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ClubsOrganizationIdRoute: ClubsOrganizationIdRoute,
  ClubsNewRoute: ClubsNewRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ViewOrganizationSlugIndexRoute: ViewOrganizationSlugIndexRoute,
  OOrganizationSlugLLeagueIdRoute: OOrganizationSlugLLeagueIdRouteWithChildren,
  ViewOrganizationSlugLLeagueIdRoute:
    ViewOrganizationSlugLLeagueIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
